services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    networks:
      - lab-net
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  backend:
    build: ./backend
    container_name: backend
    networks:
      - lab-net
    ports:
      - "9567:9567"
    depends_on:
      - elasticsearch

networks:
  lab-net:

volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      device: /path/to/host/directory  
      o: bind