version: '3.8'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - lab-net

  backend:
    build: ./backend
    container_name: backend
    networks:
      - lab-net
    ports:
      - "9567:9567"
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  esdata:

networks:
  lab-net: