services:
  elasticsearch:
    build:
      context: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build:
      context: ./backend
    ports:
      - "9567:9567"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local